services:
  mosquitto:
    image: eclipse-mosquitto
    platform: ${BUILD_ARCH}
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /opt/pet-robot/mosquitto/config/mosquitto.conf:/mosquitto/config
      - /opt/pet-robot/mosquitto/data:/mosquitto/data
      - /opt/pet-robot/mosquitto/log:/mosquitto/log
    networks:
      - internal-net