services:
  cpp_test:
    container_name: cpp_test
    image: cpp_test
    platform: ${BUILD_ARCH}
    build:
      context: ../..
      dockerfile: ../RaspberryPi/interfaces/c++/cpp_test/Dockerfile
      args:
        interface_name: "cpp_test"
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
      - internal-net
