services:
  face_controller:
    container_name: face_controller
    image: pet-robot-face-controller
    platform: ${BUILD_ARCH}
    build:
      context: ../../RaspberryPi
      dockerfile: ../RaspberryPi/interfaces/c++/face_controller/Dockerfile
      args:
        interface_name: "face_controller"
    ports:
      - "1884:1883"
    depends_on:
      - mosquitto
    restart: unless-stopped
    volumes: 
      - /sys/bus:/sys/bus
    networks:
      - internal-net
    privileged: true