services:
  c++_test:
    container_name: cpp_test
    image: cpp_test
    platform: ${BUILD_ARCH}
    build:
      context: ../../RaspberryPi
      dockerfile: ../RaspberryPi/interfaces/c++/c++_test/Dockerfile
      args:
        interface_name: "cpp_test"
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
      - internal-net
